import { ThumbailConfig } from "../types";
import Image from "../images/maths_learning.svg";

const fontFamily = `Quicksand, sans-serif`
export const defaultThumbnailConfig: ThumbailConfig = {
  width: 508,
  height: 285.75001,
  backgroundColor: "#feb743",
  fontFamily,
  x: 0,
  y: 0,
  channel: {
    fontSize: 24,
    fontColor: "#feb743",
    backgroundColor: "#2f2e41",
    x: 0,
    y: 20,
    text: "SJ INFINITY MATHS",
    fontFamily,
    width: 0,
    height: 0,
    paddingX: 10,
    paddingY: 3,
    fontWeight: "bold",
  },
  subject: {
    fontSize: 20,
    fontColor: "#feb743",
    backgroundColor: "#2f2e41",
    x: 0,
    y: 0,
    text: "Maths-II",
    fontFamily,
    width: 0,
    height: 0,
    paddingX: 10,
    paddingY: 3,
    fontWeight: "bold",
  },
  chapter: {
    fontSize: 20,
    fontColor: "#feb743",
    backgroundColor: "#2f2e41",
    x: 0,
    y: 0,
    text: "DIFFERENTIATION",
    fontFamily,
    width: 0,
    height: 0,
    paddingX: 10,
    paddingY: 3,
    fontWeight: "bold",
  },
  topic: {
    fontSize: 20,
    fontColor: "#2f2e41",
    backgroundColor: "#feb743",
    x: 300,
    y: 100,
    text: ["Parametric Differentiation", "Exercise 1.4 Q.4"],
    fontFamily,
    width: 0,
    height: 0,
    paddingX: 20,
    paddingY: 10,
    fontWeight: "normal",
  },
  image: {
    href: Image,
    x: 20,
    y: 110,
    width: 160,
    height: 160,
  },
};
